// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc_from0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BMIClient is the client API for BMI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BMIClient interface {
	GetBMI(ctx context.Context, in *WahRequest, opts ...grpc.CallOption) (*BmiResponse, error)
}

type bMIClient struct {
	cc grpc.ClientConnInterface
}

func NewBMIClient(cc grpc.ClientConnInterface) BMIClient {
	return &bMIClient{cc}
}

func (c *bMIClient) GetBMI(ctx context.Context, in *WahRequest, opts ...grpc.CallOption) (*BmiResponse, error) {
	out := new(BmiResponse)
	err := c.cc.Invoke(ctx, "/BMI/getBMI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BMIServer is the server API for BMI service.
// All implementations must embed UnimplementedBMIServer
// for forward compatibility
type BMIServer interface {
	GetBMI(context.Context, *WahRequest) (*BmiResponse, error)
	mustEmbedUnimplementedBMIServer()
}

// UnimplementedBMIServer must be embedded to have forward compatible implementations.
type UnimplementedBMIServer struct {
}

func (UnimplementedBMIServer) GetBMI(context.Context, *WahRequest) (*BmiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBMI not implemented")
}
func (UnimplementedBMIServer) mustEmbedUnimplementedBMIServer() {}

// UnsafeBMIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BMIServer will
// result in compilation errors.
type UnsafeBMIServer interface {
	mustEmbedUnimplementedBMIServer()
}

func RegisterBMIServer(s grpc.ServiceRegistrar, srv BMIServer) {
	s.RegisterService(&BMI_ServiceDesc, srv)
}

func _BMI_GetBMI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WahRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BMIServer).GetBMI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BMI/getBMI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BMIServer).GetBMI(ctx, req.(*WahRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BMI_ServiceDesc is the grpc.ServiceDesc for BMI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BMI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BMI",
	HandlerType: (*BMIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getBMI",
			Handler:    _BMI_GetBMI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
